### ISSUE TITLE
Getting "Error: 401" when trying the project locally

### ISSUE THREAD

**Issue by kofta999** [admirhusic/GoodFirstIssueFinder#6]
It seems that GitHub's API is public so it should not need Bearer auth, so if a GitHub token is not provided in env it throws a 401 Unauthorized error.

**Comment by admirhusic** [comment]
Hey @kofta999, Currently you will get 4xx, since the unauthenticated api requests are rate limited. You can create an api token in your github account and configure it in your .env file. If you need help let me know. Also Im thinking of creating a proxy endpoint which will make requests to github, so we don't need to configure the bearer token.

**Comment by kofta999** [comment]
Understood! I didn't know that unauthenticated API requests are rate limited. Thank you for clarifying it to me.
